services:
    server:
        build: .
        ports: 
            - 5050:5000
        command: npm run dev
        volumes:
            - ./src/:/app/src/
    client:
        build: client/
        ports:
            - 8080:3000
        volumes:
            - ./client/src/:/app/src/
            - ./client/public/:/app/public/

    mongodb:
        image: mongo
        volumes:
            - ./data:/data/db